[build]
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "https://web-speed-hackathon-api.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/img"
  to = "/:q"
  query = { q = ":q" }
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
